server.port=8080
server.tomcat.websocket.timeout=14400s
spring.main.allow-bean-definition-overriding=true
spring.servlet.multipart.max-file-size=80MB
spring.servlet.multipart.max-request-size=500MB
logging.level.com.example=INFO
logging.level.demo.chess=INFO
